version: '3.4'
services:
  test-database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_psswd
    volumes:
      - test-bmi-data:/var/lib/postgresql/data
      - test-bmi-backups:/var/backups/postgresql
    ports:
      - "2346:5432"
    expose:
      - '2346'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_admin -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-test:
    depends_on:
      test-database:
        condition: service_healthy
    build:
      context: ../backend/
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      DATABASE_HOST: 'test-database'
      DATABASE_NAME: 'test_db'
      DATABASE_USER: 'test_admin'
      DATABASE_PASSWORD: 'test_psswd'
      DATABASE_PORT: '5432'
      NODE_ENV: test
      JWT_SECRET: test_secret_for_stage1
      REFRESH_JWT_SECRET: test_refresh_secret_for_stage1
    volumes:
      - "../backend/node_modules:/app/node_modules_for_local_development"
      - "../backend/sync-package-lock:/app/sync-package-lock"
      - "../backend/src:/app/src"
      - "../backend/public:/app/public"
      - "test-bmi-uploads:/app/uploads"
      - "test-bmi-reports:/app/test-reports"
      - "../backend/__tests__:/app/__tests__"
      - "../backend/jest.config.js:/app/jest.config.js"
    ports:
      - "3001:3000"
    command: ["sh", "-c", "sleep 15 && npm test"]

volumes:
  test-bmi-data:
    driver: local
  test-bmi-backups:
    driver: local
  test-bmi-uploads:
    driver: local
  test-bmi-reports:
    driver: local
