version: '3.4'
services:
  database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: dso101_project
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psswd
    volumes:
      # Stage 1: Enhanced BMI data persistence
      - bmi-database-data:/var/lib/postgresql/data
      - bmi-database-logs:/var/log/postgresql
      - bmi-database-backups:/var/backups/postgresql
    ports:
      - "2345:5432"
    expose:
      - '2345'

  backend:
    depends_on:
      - database
    restart: unless-stopped
    build:
      context: ../backend/
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      DATABASE_HOST: 'database'
      DATABASE_NAME: 'dso101_project'
      DATABASE_USER: 'admin'
      DATABASE_PASSWORD: 'psswd'
      DATABASE_PORT: '5432'
      NODE_ENV: development
      JWT_SECRET: 87e3459aec28ec448228d4f990e80f14657daefc7f01a7146e1149663b30719d
      REFRESH_JWT_SECRET: 6c2723ab022250723988e5cf38e90908be10e82ee2ce802747d279f4dd7bc823
    volumes:
      - "../backend/node_modules:/app/node_modules_for_local_development"
      - "../backend/sync-package-lock:/app/sync-package-lock"
      - "../backend/src:/app/src"
      - "../backend/public:/app/public"
      # Stage 1: BMI-specific data volumes
      - "bmi-uploads:/app/uploads"
      - "bmi-user-data:/app/bmi-data"
      - "bmi-reports:/app/reports"
    ports:
      - "3000:3000"
    command: "npm run develop"

  frontend:
    depends_on:
      - backend
    restart: unless-stopped
    build:
      context: ../frontend/
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      NODE_ENV: development
    volumes:
      - "../frontend/node_modules:/app/node_modules_for_local_development"
      - "../frontend/sync-package-lock:/app/sync-package-lock"
      - "../frontend/src:/app/src"
    ports:
      - "3010:3010"
    command: "npm run develop"

volumes:
  # Stage 1: BMI Data Volume Configuration
  bmi-database-data:
    driver: local
  bmi-database-logs:
    driver: local
  bmi-database-backups:
    driver: local
  bmi-uploads:
    driver: local
  bmi-user-data:
    driver: local
  bmi-reports:
    driver: local
